version: '3.7'
services:
  access-sphere:
    container_name: access-sphere-stg
    image: ${DOCKER_REPOSITORY}:${APP_VERSION}
    hostname: access.sphere.service.stg
    ports:
      - "8007:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DATABASE_JDBC_URL=${DATABASE_JDBC_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - APP_ENV=${APP_ENV}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - LOGBACK_FILE=${LOGBACK_FILE}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - STRAPI_ACTIVE=${STRAPI_ACTIVE}
      - STRAPI_URL=http://stg.app.strapi.cms:1337
      - STRAPI_AUTH_TOKEN=${STRAPI_AUTH_TOKEN}
      - TECH_USERNAME=${TECH_USERNAME}
      - TECH_PASSWORD=${TECH_PASSWORD}
      - CORS_ENABLED=${CORS_ENABLED}
      - CORS_NOT_FILTER=${CORS_NOT_FILTER}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}
    volumes:
      # Monta il volume "microservice" nella cartella /secrets (in sola lettura)
      - microservice:/secrets:ro
    deploy:
      replicas: 1  # Cambia il numero di repliche a seconda delle tue esigenze
    networks:
      docker-network:
        aliases:
          - access.sphere.service.stg

networks:
  docker-network:
    external: true

volumes:
  microservice:
    external: true