env: Local
spring:
  application:
    name: access-sphere
    starter-log: true # Show Started Application
  r2dbc:
    url: r2dbc:mysql://localhost:3306/access_sphere
    username: root
    password: root
    initialization: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/access_sphere
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Level of LOG
logging:
  config: ${LOGBACK_FILE:}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico"
  rate-limiting:
    shouldFilter: "*/users/change/password,*/users/change/password/request"
  session-id:
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico"
    generateSessionURI: "/v1/oAuth/2.0/authorize,*/users/register"
    bearerNotFilter: "*/v1/oAuth/2.0/login/*,*/users/register,*/v1/users/change/password/*,*/v1/users/change/password,*/favicon.ico"
    logoutURI: "*/v1/oAuth/2.0/logout"

rest:
  client:
    strapi:
      active: true
      baseUrl: https://strapi.hostwebserver.site
      bearer: ${STRAPI_AUTH_TOKEN}
      path:
        clientId: /api/Oauthclientids
        registerUser: /api/auth/local/register
        getUserByEmail: /api/users
        login: /api/auth/local
        getRefreshToken: /api/auth/token/request
        userInfo: /api/users/me
        refreshToken: /api/auth/token
        logout: /api/auth/revoke
        updateUser: /api/users/:userId
        getTemplate: /api/email-templates
    email-sender:
      baseUrl: https://email-sender.giovannilamarmora.com
      path:
        sendEmailUrl: /v1/send-email

app:
  version: @project.version@
  cache:
    active: false
    cron: 0 0 1 * * *
  exception:
    stacktrace: true # Active StackTrace in Response