env: ${APP_ENV} # Used for Google Cloud LOG
spring:
  application:
    name: access-sphere
    starter-log: true # Show Started Application
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_JDBC_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Level of LOG
logging:
  logback:
    # Logging on LogTails
    logTail: # Disabled
      active: false
    google-cloud:
      active: true
  level:
    io.github.giovannilamarmora: ${LOGGING_LEVEL}
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

rest:
  client:
    strapi:
      active: true
      baseUrl: http://app.strapi.cms:8080
      bearer: ${STRAPI_AUTH_TOKEN}
      path:
        clientId: /api/Oauthclientids
        registerUser: /api/auth/local/register
        getUserByEmail: /api/users
        login: /api/auth/local
        getRefreshToken: /api/auth/token/request
        userInfo: /api/users/me
        refreshToken: /api/auth/token
        updateUser: /api/users/:userId

app:
  version: @project.version@
  cache:
    active: false
  shouldNotFilter: "**/swagger-ui/index.html,/swagger-ui/swagger-initializer.js,/v3/api-docs,/v3/api-docs/**"
  exception:
    stacktrace: true # Active StackTrace in Response
  # Cors status
  cors: # Disabled
    enabled: false