CREATE TABLE IF NOT EXISTS ASS_CLIENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID VARCHAR(255) NOT NULL UNIQUE,
    EXTERNAL_CLIENT_ID VARCHAR(255) UNIQUE,
    CLIENT_SECRET VARCHAR(255),
    SCOPES VARCHAR(255),
    REDIRECT_URI VARCHAR(255),
    ACCESS_TYPE VARCHAR(255),
    OAUTH_TYPE VARCHAR(255),
    TOKEN_TYPE VARCHAR(255),
    JWT_SECRET VARCHAR(255),
    JWT_EXPIRATION BIGINT,
    JWE_SECRET VARCHAR(255),
    JWE_EXPIRATION BIGINT
);
